# Generated by Django 5.1.7 on 2025-04-01 16:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('APP', 'Appetizers'), ('MAIN', 'Main Courses'), ('SIDE', 'Side Dishes'), ('DESS', 'Desserts'), ('BEV', 'Beverages'), ('SPEC', 'Specialties')], help_text='Type of menu category', max_length=4, unique=True)),
                ('display_name', models.CharField(help_text='User-friendly display name', max_length=50)),
                ('short_description', models.CharField(blank=True, help_text='Brief description for menu listings', max_length=200)),
                ('long_description', models.TextField(blank=True, help_text='Detailed description for category pages')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order in which category appears in menu')),
                ('active', models.BooleanField(default=True, help_text='Whether this category appears in menus')),
                ('image_url', models.URLField(blank=True, help_text='URL of category image', max_length=500, null=True, validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['category__display_order', 'display_order', 'name'], 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AddField(
            model_name='dish',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this dish appears on menus'),
        ),
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Approximate calorie count', null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this dish was added to the menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order in which dish appears in category'),
        ),
        migrations.AddField(
            model_name='dish',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed description with ingredients, preparation, etc.'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of high-quality dish image', max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_gluten_free',
            field=models.BooleanField(default=False, help_text='Is this gluten-free?'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_spicy',
            field=models.BooleanField(default=False, help_text='Is this dish spicy?'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_vegan',
            field=models.BooleanField(default=False, help_text='Is this a vegan dish?'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_vegetarian',
            field=models.BooleanField(default=False, help_text='Is this a vegetarian dish?'),
        ),
        migrations.AddField(
            model_name='dish',
            name='preparation_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Average preparation time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for menu listings', max_length=200),
        ),
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL of thumbnail image', max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='dish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this dish was last modified'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(help_text='Name of the dish as it appears on the menu', max_length=200),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in local currency', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Menu category this dish belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menu.category'),
        ),
    ]
